const accountModel = require("./account/account.model")
const artistModel = require("./artist/artist.model")
const categoryModel = require("./category/category.model")
const musicModel = require("./music/music.model")
const albumModel = require("./album/album.model")
const savedModel = require("./saved/saved.model")
const historyModel = require("./history/history.model")
const playlistModel = require("./playlist/playlist.model")
const playlistMusicModel = require("./playlist/playlist_music.model")
const likeMusicModel = require("./like/like.model")
const followModel = require("./follow/follow.model")
const moodModel = require("./mood/mood.model")
const eventModel = require("./event/event.model")
const shortMusicModel = require("./shorts/shortMusic.model")
const episodesModel = require("./episodes/episodes.model")
const saveModel = require("./save/save.model")

module.exports = { accountModel, artistModel, categoryModel, musicModel, albumModel, historyModel, savedModel, playlistModel, playlistMusicModel, likeMusicModel, followModel, moodModel, eventModel, shortMusicModel, episodesModel, saveModel }